const authActionTypes = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE"
}

const screenerActionTypes = {
    GET_SCREENED_DATA_REQUEST: "GET_SCREENED_DATA_REQUEST",
    GET_SCREENED_DATA_SUCCESS: "GET_SCREENED_DATA_SUCCESS",
    GET_SCREENED_DATA_FAILURE: "GET_SCREENED_DATA_FAILURE",
    SET_EXPORTING_TICKERS: "SET_EXPORTING_TICKERS"
}

const portfolioActionTypes = {
    SET_PORTFOLIO_REQUEST: 'SET_PORTFOLIO_REQUEST',
    SET_PORTFOLIO_SUCCESS: 'SET_PORTFOLIO_SUCCESS',
    SET_PORTFOLIO_FAILURE: 'SET_PORTFOLIO_FAILURE'
}

const profileActionTypes = {
    CREATE_NEW_PORTFOLIO_REQUEST: "CREATE_NEW_PORTFOLIO_REQUEST",
    CREATE_NEW_PORTFOLIO_SUCCESS: "CREATE_NEW_PORTFOLIO_SUCCESS",
    CREATE_NEW_PORTFOLIO_FAILURE: "CREATE_NEW_PORTFOLIO_FAILURE",
    GET_USER_PORTFOLIOS_REQUEST: 'GET_USER_PORTFOLIOS_REQUEST',
    GET_USER_PORTFOLIOS_SUCCESS: 'GET_USER_PORTFOLIOS_SUCCESS',
    GET_USER_PORTFOLIOS_FAILURE: 'GET_USER_PORTFOLIOS_FAILURE',
    ADD_TO_PORTFOLIO_REQUEST: 'ADD_TO_PORTFOLIO_REQUEST',
    ADD_TO_PORTFOLIO_SUCCESS: 'ADD_TO_PORTFOLIO_SUCCESS',
    ADD_TO_PORTFOLIO_FAILURE: 'ADD_TO_PORTFOLIO_FAILURE',
    REMOVE_FROM_PORTFOLIO_REQUEST: 'REMOVE_FROM_PORTFOLIO_REQUEST',
    REMOVE_FROM_PORTFOLIO_SUCCESS: 'REMOVE_FROM_PORTFOLIO_SUCCESS',
    REMOVE_FROM_PORTFOLIO_FAILURE: 'REMOVE_FROM_PORTFOLIO_FAILURE',
    DELETE_PORTFOLIO_REQUEST: 'DELETE_PORTFOLIO_REQUEST',
    DELETE_PORTFOLIO_SUCCESS: 'DELETE_PORTFOLIO_SUCCESS',
    DELETE_PORTFOLIO_FAILURE: 'DELETE_PORTFOLIO_FAILURE'
}


export { authActionTypes, screenerActionTypes, portfolioActionTypes, profileActionTypes }